# Generated by Django 5.1.1 on 2024-09-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='receita',
            new_name='fk_receita',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='usuario',
            new_name='fk_usuario',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='categoria',
            new_name='fk_categoria',
        ),
        migrations.AlterField(
            model_name='rating',
            name='nota',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
