# Generated by Django 5.1.1 on 2024-09-26 19:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receita", "0004_alter_recipe_tempo_preparo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Rating",
            new_name="Avaliacao",
        ),
        migrations.RenameModel(
            old_name="Category",
            new_name="Categoria",
        ),
        migrations.RenameModel(
            old_name="Recipe",
            new_name="Receita",
        ),
    ]
