# Generated by Django 5.1.1 on 2024-09-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receita", "0005_rename_rating_avaliacao_rename_category_categoria_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receita",
            name="fk_categoria",
        ),
        migrations.AddField(
            model_name="receita",
            name="fk_categoria",
            field=models.ManyToManyField(
                related_name="categorias", to="receita.categoria"
            ),
        ),
    ]
