# Generated by Django 5.1.1 on 2024-10-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0006_remove_receita_fk_categoria_receita_fk_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
